<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "zh_basic_service"
 *
 * Auto generated by Extension Builder 2017-10-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Basic Service',
    'description' => 'Basic Service',
    'category' => 'misc',
    'author' => 'sunnyahua',
    'author_email' => 'sunnyahua@126.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
